version: '3'
services:
    backend:
        build:
            context: ./workspace/power_model_system
            dockerfile: Dockerfile
        hostname: 247-chenzhu
        ports:
          - '29001:8888'
          - '29002:22'
          - '29003:8010'
        tty: true # 打开这个选项使得 bash 可以在后台运行
        volumes:
          - "${PWD}/workspace/power_model_system:/workspace/power_model_system"
            #- "/lab-pool/LabProjects/$PROJECT_ALIAS/$STAGE/workspace:/workspace/"
          - "/lab-pool/Jupyter_Workspace/hdm/data:/workspace/data"
        depends_on:
          - redis
          - mysql
          - influxdb
    redis:  # redis 默认端口 6379
      image: redis:latest
      ports:
          - "6379:6379"
      volumes:
        - "./redis/data:/data"
        - "./redis/redis.conf:/etc/redis/redis.conf"
      command:  redis-server /etc/redis/redis.conf
    frontend:
      image: nginx:alpine
      volumes:
        - "${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          # - "./etc/ssl:/etc/ssl"
        - "${PWD}/frontend:/var/www/html"
      ports:
          - "80:80"
      command: /bin/sh -c "nginx -g 'daemon off;'"
      restart: always
      depends_on:
          - backend
    influxdb: #  8086
      image: influxdb:1.7.4
      ports:
          - "8086:8086"
      environment:
        DOCKEINFLUXDB_INIT_USERNAME: root
        DOCKER_INFLUXDB_INIT_PASSWORD: root
      volumes:
          - "${PWD}/influxdb/data:/var/lib/influxdb"
    mysql: # 3306
      image: mysql:5.7.20
      ports:
          - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
          - "${PWD}/mysql/data:/var/lib/mysql"
          - "${PWD}/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d"
# 设置默认网络为 存在的 default
networks:
  default:
    driver: bridge