version: '3'
services:
    backend:
        build:
            context: ./workspace/power_model_system
            dockerfile: Dockerfile
        hostname: 251-production
        ports:
          - '29014:8888'
          - '29015:22'
          - '29016:8010'
        tty: true # 打开这个选项使得 bash 可以在后台运行
        volumes:
          - "${PWD}/workspace/power_model_system:/workspace/power_model_system"
          - "/mnt/nfs-storage/hdm/data:/workspace/data"
          - "/mnt/nfs-storage/hdm/hd_ws:/workspace/hd_ws"
        deploy:
          resources:
            limits:
                cpus: "40.00"
                memory: 120G
            reservations:
                memory: 20G
                devices:
                  - driver: nvidia
                    capabilities: [gpu] # 默认使用所有设备
        depends_on:
          - redis
          - mysql
          - influxdb
    redis:  # redis 默认端口 6379
      command:  redis-server /etc/redis/redis.conf
      image: redis:latest
      ports:
          - "6385:6379"
      volumes:
        - "${PWD}/redis/data:/data"
        - "${PWD}/redis/redis.conf:/etc/redis/redis.conf"
    frontend:
      image: nginx:alpine
      volumes:
          - "${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          # - "./etc/ssl:/etc/ssl"
          - "${PWD}/frontend:/var/www/html"
      ports:
          - "85:80"
      command: /bin/sh -c "nginx -g 'daemon off;'"
      restart: always
      depends_on:
          - backend
    influxdb: #  8086
      image: influxdb:1.7.4
      ports:
          - "8091:8086"
      environment:
        DOCKEINFLUXDB_INIT_USERNAME: root
        DOCKER_INFLUXDB_INIT_PASSWORD: root
      volumes:
        - "${PWD}/influxdb/data:/var/lib/influxdb"
    mysql: # 3306
      image: mysql:5.7.20
      ports:
          - "3311:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - "${PWD}/mysql/data:/var/lib/mysql"
        - "${PWD}/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d"
      restart: always
# 设置默认网络为 存在的 default
networks:
  default:
    driver: bridge